### ISSUE TITLE
Select multiple files for exclusion by prefix

### ISSUE THREAD

**Issue by ohlinn** [dy-sh/obsidian-consistent-attachments-and-links#10]
I'm using the [Zoottelkeeper Plugin](https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin) which generates and update an index note for each folder, and it's possible to set a prefix for the name of these notes. This plugin lists subfolders and notes as a link, so the subfolders, as they don't exist as files, are detected by this plugin as inconsistencies.
That made me think that It could be useful to have the possibility of selecting multiple files for exclusions by the first characters of the name of a file, instead of setting manually each of them.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0
