### ISSUE TITLE
Ошибка при создании нового файла

### ISSUE THREAD

**Issue by Gray388** [dy-sh/obsidian-consistent-attachments-and-links#100]

**Comment by Gray388** [comment]
Здравствуйте. При создании нового файла если пытаться  его переименовать появляется ошибка, и файл не создается.
В консоли выводит следующее:
Error: ENOENT: no such file or directory, rename 'H:\_______________\Без названия 3.md' -> 'H:\___________\Без названия 4.md'
    at async Object.rename (node:internal/original-fs/promises:779:10) plugin:consistent-attachments-and-links:585 Error: ENOENT: no such 

После отключения плагина все работает.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.13.0
