### ISSUE TITLE
При создании нового файла, возникает ошибка

### ISSUE THREAD

**Issue by Gray388** [dy-sh/obsidian-consistent-attachments-and-links#101]
Здравствуйте. При создании нового файла, если попытаться его переименовать, возникает ошибка, и файл не создается.
В консоли выводит следующее:
При создании нового файла, если попытаться его переименовать, возникает ошибка
Error: ENOENT: no such file or directory, rename 'H:\______________\Без названия 3.md' -> 'H:\____________\Без названия 4.md'
    at async Object.rename (node:internal/original-fs/promises:779:10)
plugin:consistent-attachments-and-links:585

После отключения плагина все работает.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.13.0
