### ISSUE TITLE
Plugin reminds me the attachments will not be deleted

### ISSUE THREAD

**Issue by whoubeizin** [dy-sh/obsidian-consistent-attachments-and-links#104]
After I updated all my plugins yesterday, everytime I creat or delete note now, the plugin will reminds me that the attachments will not be deleted because it was used by other note. 

This really upset me. I guess maybe something went wrong with the plugin.

plugin version:3.12.0

screenshoot：![2024-08-25_084024](https://github.com/user-attachments/assets/b5b62bbd-4da8-4bd5-8430-177110916883)
screen recording：https://github.com/user-attachments/assets/1490f246-4963-4f81-b710-617febbec2a7

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.13.0

**Comment by whoubeizin** [comment]
thanks！
