### ISSUE TITLE
Новая папка со старым именем

### ISSUE THREAD

**Issue by serggrod** [dy-sh/obsidian-consistent-attachments-and-links#105]
[Видео со странными действиями](https://drive.google.com/file/d/1Le7Ms-QCK14XzSs8e84nJJT2toYpWyBg/view?usp=drive_link)

Суть проблемы кратко: Как ты можешь видеть на видео при переименовании папки автоматически создается другая папка со старым именем, зачем мен не понятно. Я думаю что это баг.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.13.1
