### ISSUE TITLE
Пустая подпапка

### ISSUE THREAD

**Issue by serggrod** [dy-sh/obsidian-consistent-attachments-and-links#106]
[Видео создания - Пустая подпапка](https://drive.google.com/file/d/1LgaJTVSOoTMlE2LXUiJ97IJC6_AVbg0f/view?usp=drive_link)

Суть проблемы: при переносе файла в папку в которой нет подпапки для attachment, даже если переносимый файл совершенно пуст создается пустая подпапка для attachment, что кажется совершенно не логичным, ведь если я в папке не планирую хранить файлы с прикрепленными вложениями то и подпапка мне не нужна

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.13.1
