### ISSUE TITLE
При переименовании файла, ссылки на него не обновляются

### ISSUE THREAD

**Issue by serggrod** [dy-sh/obsidian-consistent-attachments-and-links#107]
[Видео с проблемой](https://drive.google.com/file/d/1Lw-RjKQGeQjHqA2mcf7CfGR2jYRIyeHR/view?usp=drive_link)

При переименовании файла ссылка на него не обновляется и снова создается пустая папка

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.13.1
