### ISSUE TITLE
Links get changeed to embeds all the time

### ISSUE THREAD

**Issue by au-voltzzz** [dy-sh/obsidian-consistent-attachments-and-links#108]
I am not sure how to explain this issue properly. With the older versions of this plugin files could be given a name like `[Name for Note](_attachments/File.mp4)`. However, these files are now always turned into embeded files which makes it harder to open them in the default app for the OS. They are now changed to `![](_attachments/File.mp4)`.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.13.2
