### ISSUE TITLE
Unable to load/enable plugin v3.13.3 on Obsidian Android 1.6.7

### ISSUE THREAD

**Issue by ericjding** [dy-sh/obsidian-consistent-attachments-and-links#109]
I'm using Obsidian 1.6.7 on Android. I've been using it happily for some time with the consistent attachments and links plugin. So... first of all, thank you!

Today, however, I decided to tap on the button to update the plugin to the latest version from v1.3.0 to v3.13.3, and now Obsidian complains that it cannot load the plugin when I try to enable it. What can I do to fix this? Thanks!

**Comment by toddlund3355** [comment]
I am having the same issue with the same versions on Android (both installed today). When enabling the plug-in, I get "Failed to load plugin "consistent-attachments-and-links". It works great on Windows.

**Comment by PiraSiraly** [comment]
Same problem on my Android.
Obsidian is up to date, the latest plugin version cannot be activated. 
However, there were also problems or limitations with the previous versions - full functionality has only been available under Windows since 3.0.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.14.0
