### ISSUE TITLE
Add check for links that starts with # 

### ISSUE THREAD

**Issue by dy-sh** [dy-sh/obsidian-consistent-attachments-and-links#11]
The plugin does not find problems when the link starts with a # and leads to a non-existent title. The check only works when the link starts with a filename.

**Comment by derwish-pro** [comment]
It looks like the link that has the file name at the beginning is not checked, but it is a link to the current note.

**Comment by mnaoumov** [comment]
Fixed in Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0
