### ISSUE TITLE
Pasted image in Canvas file appear in wrong folder (folder belonging to file of previous selected tab)

### ISSUE THREAD

**Issue by gn4881** [dy-sh/obsidian-consistent-attachments-and-links#111]
My setting:
Location for new attachment: "./${filename}_(附件)"

Issue:
1. I selected 1st tab (file location: Folder 1/ A.md)
2. I switch to 2nd tab (file location: Folder 2/ B.canvas) & pasted an image in the canvas file. 
3. I expect the image to be stored in "Folder 2/B_(附件)" (B is a .canvas file)
4. But the image is stored in "Folder 2/A_(附件)" (A is an .md file)
5. It seems your software know the correct file location but ignore .canvas file's name for some reason. Hope I explain my point clearly to help you fix the issue.

**Comment by mnaoumov** [comment]
This plugin doesn't have a setting `Location for new attachment` starting from `v3.0.0`. See [README](https://github.com/dy-sh/obsidian-consistent-attachments-and-links?tab=readme-ov-file#attachment-subfolder-setting-)

Did you confuse with https://github.com/RainCat1998/obsidian-custom-attachment-location ?
