### ISSUE TITLE
[Feature Request] Custom size for pasted image

### ISSUE THREAD

**Issue by gn4881** [dy-sh/obsidian-consistent-attachments-and-links#112]
Desired result:
1. I pasted an high resolution image.
2. Automatically the image is named as "image.png"
3. Desired result: "image.png|300" (The big picture appear as smaller size without losing the original quality of the picture, we can open the original picture to view the fullest size)

**Comment by mnaoumov** [comment]
Current plugin doesn't handle `paste` event. Are you confusing it with https://github.com/RainCat1998/obsidian-custom-attachment-location ?
