### ISSUE TITLE
"Delete Empty Folders" does not work on Windows

### ISSUE THREAD

**Issue by PiraSiraly** [dy-sh/obsidian-consistent-attachments-and-links#113]
When I run “Delete Empty Folders” on my Android, all empty folders are deleted.
However, when I run the same command on Windows, empty folders are not deleted.

If I move the last .md with attachment out of a folder, it and also the empty attachment folder are deleted correctly on Windows and Android.

I think that all empty folders should also be deleted under Windows when executing the “Delete Empty Folders” command, regardless of whether an .md was moved or not.

**Comment by mnaoumov** [comment]
@PiraSiraly cannot reproduce. Please retest on the latest version. If the issue persists, please attach the test vault

**Comment by PiraSiraly** [comment]
In the latest version, I can no longer reproduce the situation I described.
However, the "Delete Unused Attachments with Note" function no longer works. 
I have tried it on Windows and Android, in my Vault and in a fresh TestVault.
Attachments are not automatically deleted when I delete an md.

However, the folders are deleted correctly after they are empty - but after about 2min waiting time without reaction of the plugin I manually performed "Reorganize Vault".

**Comment by mnaoumov** [comment]
@PiraSiraly cannot reproduce the issue. Please attach the copy of the vault and the video with the issue

**Comment by PiraSiraly** [comment]
Here is a short video and the test vault. I made the recorded test under Windows.
The attachments were deleted correctly, but not the folders - not even after using the command.

https://github.com/user-attachments/assets/8d43f848-da52-4bb1-a8f2-3c00cc9faa46

[Test.zip](https://github.com/user-attachments/files/17213427/Test.zip)

**Comment by mnaoumov** [comment]
@PiraSiraly Could not reproduce the issue on the vault attached. Please retest
