### ISSUE TITLE
Несколько ошибок в одном видио

### ISSUE THREAD

**Issue by serggrod** [dy-sh/obsidian-consistent-attachments-and-links#114]
Ошибки в работе
1. При переименовании файла не происходит переименования ссылки, т.е. не работает опция - Update Backlink Text
2. При переносе файла в подпапку, прикреплённый файл (картинка) выбрасывается в корень хранилища, а должна, по крайней мере так было раньше , переноситься в подпапку той папки в которой находиться файл.
3. При удалении файла, к которой был прикреплён attached, сам attached не удаляется, хотя к другим файлом он не прикреплен

[Смотри видео](https://drive.google.com/file/d/1TQI7EaY2T9OUK_-Dn8N-ApGaI0HyD708/view?usp=sharing )

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.20.0
