### ISSUE TITLE
[BUG] with wikilinks display text 

### ISSUE THREAD

**Issue by marconoris** [dy-sh/obsidian-consistent-attachments-and-links#115]
After the last update, when I move a file, the wikilink display text of the moved file in notes, disappears or changes to the path of the file. Example: it changes from [[Docs/Defs/Hopis|Hopis]] to [[../Fragmentarium/Hopis]] or [[../Fragmentarium/Hopis|../Fragmentarium/Hopis]].

The problem disappears when I deactivate the plugin, but I'm not sure if it's a compatibility issue with other plugins...

**Comment by mnaoumov** [comment]
@marconoris you didn't follow the required steps of the bug report

**Comment by marconoris** [comment]
Sorry. 

I'm sure it's a conflict with another plugin, I've posted here just in case someone else has the same thing going on. Anyway here's the video https://capture.dropbox.com/Qakl4qB3KRYQzTXz (it's the latest Insider version of Obsidian 1.7.3)

**Comment by mnaoumov** [comment]
@marconoris please follow the template, it was there for a reason

**Comment by marconoris** [comment]
Never mind

**Comment by mnaoumov** [comment]
Video is not enough. Copy of your vault would help to find why is it conflicting with other plugins

**Comment by marconoris** [comment]
Here the new video with a sample vault (Obsidian Sandbox Vault): https://capture.dropbox.com/UhRqfKO3cu6I2xT5
 
[Obsidian Sandbox.zip](https://github.com/user-attachments/files/17135806/Obsidian.Sandbox.zip)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.21.7
