### ISSUE TITLE
[BUG] Other notes and attachments are getting deleted on single note deletion with default settings

### ISSUE THREAD

**Issue by CHerSun** [dy-sh/obsidian-consistent-attachments-and-links#117]
A clear and concise description of the bug.

- Please attach a video of the issue.
- Please attach a sample vault where the issue can be reproduced.

New installation of the plugin, everything set to default. I localized attachments for 1 specific note and copied that note + attachments to another vault. Once I was sure I do have the note working finely and with all attachments - I've decided to delete that one single note (right click on nav tree in Obsidian + delete).

Problem is - lots of stuff got deleted:
- a dozen of OTHER notes
- a few templates
- lots of images

Thankfully, I have a sync with NextCloud, which deletes files to the Trash folder, so I was able to recover. Incomplete screenshot of what was deleted:

![image](https://github.com/user-attachments/assets/d2dba62d-8f79-4092-9ba2-feaefb4645fa)

Obsidian + Git + Mobile was the one that I was deleting and the only one (no multi-selection).

I wasn't able to find a log - what exactly triggered the action and why, but this plugin is the latest addition. Still checking this, not sure if there's any extra info tbh.

**Comment by CHerSun** [comment]
Default settings include auto-deletion of attachments. Maybe some bug there? I've disabled that temporarily. Trying to find out the culprit, will update later.

**Comment by mnaoumov** [comment]
@CHerSun You didn't follow the issue template

**Comment by CHerSun** [comment]
Made an extra test after recovery:
- keeping all other plugins to their original configs.  
- disabled ONLY this plugin, no changes to any other plugin or setting
- deleted the same note again - only the note was deleted (its 3 attachments intact; no other notes affected). ✔ expected behavior
- recovered the file back
- enabled ONLY this plugin
- deleted the same note again - ❌ half of the vault is gone again.

**Comment by CHerSun** [comment]
> @CHerSun You didn't follow the issue template

If you mean the vault - I will try to make a reproducible vault a bit later. Was busy recovering.

**Comment by CHerSun** [comment]
[Consistent-attachments-vault.zip](https://github.com/user-attachments/files/17329333/Consistent-attachments-vault.zip)

Ok, I've stripped down sensitive info and confirmed, that the bug is present in this vault. 

To test - delete `HowTo\Obsidian\Obsidian + Git + Mobile.md`

**Comment by CHerSun** [comment]
@mnaoumov really, a data loss marked as completed? Up to you, I'll just delete this plugin.

**Comment by mnaoumov** [comment]
@CHerSun in order to fix the problem I need to see it first, that's why I'm asking the video to help me

**Comment by mnaoumov** [comment]
@CHerSun thanks

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.21.7
