### ISSUE TITLE
An unhandled error occured

### ISSUE THREAD

**Issue by KleiDav** [dy-sh/obsidian-consistent-attachments-and-links#119]
Hello

Since several days I have that error that pops up each time I'm doing a change on a note :

![image](https://github.com/user-attachments/assets/b2ff4307-09a1-4f57-a3b1-ba60a3820224)

And here's a screenshot of the console log :

![image](https://github.com/user-attachments/assets/6d7c6ac4-1b82-4283-bc0c-40fc45f315d6)

I don't know since when I have the issue. Could be since latest upgrade to Obsidian v1.7.4
I think they've changed things in the way the Sync module is working (which I'm using)

**Comment by pablo-hp** [comment]
Same error here.
I hope the dev can figure out what's going on.

**Comment by sxr1223** [comment]
Same issue. I anasysis the javascript code in release. The error may come from function `saveNote`. I move note to reproduce this error. After move, the function `saveNote` with the new position for note generate this error. I don't know how to repair error, but I do hope dev can repair this.

**Comment by irocreate** [comment]
I'm having the same issue as well. @
![Screenshot 2024-10-30 112605](https://github.com/user-attachments/assets/902057a5-74dc-4337-aa27-9527dcab26f1)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.21.5
