### ISSUE TITLE
Collect breaking due to /\: characters

### ISSUE THREAD

**Issue by jt196** [dy-sh/obsidian-consistent-attachments-and-links#12]
Just having a little play around with this - great plugin @derwish-pro. 

One thing I've noticed is that on collecting a large folder of files, if any of them have weird characters`:\/` , it'll break. The console is showing up an error but there's no feedback. 

It'd be nice if the script would continue to run rather than crashing - I guess whatever the JS equivalent of `try:` in Python is. 

What would be even nicer is some sort of error report - perhaps in the root folder alongside the *consistant-report* file, or some sort of visual feedback to tell the user that things have gone pear-shaped. 

Got about halfway with a bunch of files then had to start again unfortunately as things weren't working well (also due to spacing in the URLs).

**Comment by derwish-pro** [comment]
Thank you for your feedback.

**Comment by mnaoumov** [comment]
I don't think such characters in file names are allowed in latest Obsidian versions
