### ISSUE TITLE
[BUG] Why this link is bad

### ISSUE THREAD

**Issue by muzhi1991** [dy-sh/obsidian-consistent-attachments-and-links#121]
### Description

The command I used: Replace all wikilinks with markdown links Generated links

`[[20230716#GQA Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints|GQA]]`--> `[GQA](20230716.md#GQA%20Training%20Generalized%20Multi-Query%20Transformer%20Models%20from%20Multi-Head%20Checkpoints)`

PS: this file and section all exists. can preview in obsidian when my mouse point it

But check vault consistency gives this link error
<img width="771" alt="image" src="https://github.com/user-attachments/assets/a8cef5a3-fcf9-4fbc-b615-6dc6618a9b8d">

### Steps to Reproduce

1. write [[20230716#GQA Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints|GQA]]·
2. run  Replace all wikilinks with markdown links 
3. run check vault consistency

### Expected Behavior

good links not show in report

### Actual Behavior

bad links in report

### Environment Information

- **Plugin Version**: 3.21.11
- **Obsidian Version**: 1.7.7
- **Operating System**:  macOS 15.1.1

### Attachments

- Please attach a video showing the issue
- Please attach a sample vault where the issue can be reproduced

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by mnaoumov** [comment]
@muzhi1991 you didn't do what is required before clicking checkboxes

I cannot reproduce the issue
