### ISSUE TITLE
[FR] Support filtering by file extension and support collecting attachments for a specific folder

### ISSUE THREAD

**Issue by Moyf** [dy-sh/obsidian-consistent-attachments-and-links#123]
### Description

Hi! 
I would like to propose two new feature requests.

## [1] Filter by file name
Currently, all attachments—such as `xlsx` or `css` files—are moved according to the rules, and I would like these files to remain in their original locations.
So, could you add an option in the settings to filter by file extension... 
or even better, support filtering using regular expressions?
![image](https://github.com/user-attachments/assets/30b69248-1e6c-4bc6-b6a7-28955a38c5b6)

## [2] Collect all attachments in a specific folder
Currently, the plugin provides two Collect commands: 
for the current file and for the entire vault.
![image](https://github.com/user-attachments/assets/1705ba88-b917-4abe-beb5-23509cd425d0)

Sometimes I only move files within a folder; could you add a command that **only performs the Collect operation for the folder where the current note is located**?
If possible, it could also be added to the right-click menu of the folder.

### Details

These are feature requests without reproduction steps.

### Desired Behavior

I hope that:

1. The filtering rules in the plugin settings can be configured using regular expressions, allowing for greater flexibility in filtering files.
2. I can perform the Collect operation on just one specific folder, rather than on the entire library or current files.

### Current Behavior

These features are not currently available.

### Attachments

[TestVault.zip](https://github.com/user-attachments/files/18141026/TestVault.zip)

https://github.com/user-attachments/assets/3dbb7be0-ac26-44c6-bf8b-16c8cd11435c

### Confirmations

- [X] I attached a video showing the current behavior
- [X] I attached a sample vault where the desired Feature Request could be applied
- [X] I have tested the issue with the latest version
- [X] I have checked for existing Feature Requests

**Comment by mnaoumov** [comment]
Added in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.22.0

**Comment by Moyf** [comment]
> Added in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.22.0

Bravo! Thank you so much! It's really useful! 👍
