### ISSUE TITLE
Feature Request: Rename attachments base on note title or note filename

### ISSUE THREAD

**Issue by magi44ken** [dy-sh/obsidian-consistent-attachments-and-links#14]
Hi,

Can you consider adding a feature to rename all the attachments (images, videos, audio, etc.) within a document base on note title or note filename which make it lot easier to search for attachments for deleting or renaming, etc.. 

There should be a settings to allow user to chose either base on note title or note filename. Another settings to choose which rename format to use. There are two formats to choose from.

**Rename Format 1**

My Christmas Wishlist.md

- My Christmas Wishlist-0001.jpg
- My Christmas Wishlist-0002.jpg
- My Christmas Wishlist-0001.mp4
- My Christmas Wishlist-0002.mp4
- My Christmas Wishlist-0003.mp4
- My Christmas Wishlist-0001.mp3
- My Christmas Wishlist-0002.mp3
etc..

Grocery List.md

- Grocery List-0001.jpg
- Grocery List-0002.jpg
- Grocery List-0001.mp4
- Grocery List-0002.mp4
- Grocery List-0003.mp4
- Grocery List-0001.mp3
- Grocery List-0002.mp3
etc..

**Rename Format 2**

My Christmas Wishlist.md

- My Christmas Wishlist-0001.jpg
- My Christmas Wishlist-0002.jpg
- My Christmas Wishlist-0003.mp4
- My Christmas Wishlist-0004.mp4
- My Christmas Wishlist-0005.mp4
- My Christmas Wishlist-0006.mp3
- My Christmas Wishlist-0007.mp3
etc..

Grocery List.md

- Grocery List-0001.jpg
- Grocery List-0002.jpg
- Grocery List-0003.mp4
- Grocery List-0004.mp4
- Grocery List-0005.mp4
- Grocery List-0006.mp3
- Grocery List-0007.mp3
etc..

Thanks.

**Comment by mnaoumov** [comment]
Consider the following plugin https://github.com/RainCat1998/obsidian-custom-attachment-location

**Comment by mnaoumov** [comment]
Implemented in part in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.8: attachments can be put in a `${filename}` folder, but the attachment files themselves are not renamed.
