### ISSUE TITLE
Plugin doesn't support mobile?

### ISSUE THREAD

**Issue by necopinus** [dy-sh/obsidian-consistent-attachments-and-links#17]
There's no warning that the consistent attachments and links plugin does not support mobile, but once installed it fails to enable (at least for Obsidian 1.0.5 running on iOS 15.3.1).

It would be great if this plugin supported mobile as well as the desktop!

**Comment by marconoris** [comment]
The same here!

**Comment by BobWs** [comment]
Same!

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
