### ISSUE TITLE
Feature Request : Convert All links to Wikilinks and move resources to common folder

### ISSUE THREAD

**Issue by alanalvarado** [dy-sh/obsidian-consistent-attachments-and-links#18]
I just came to obsidian from Evernote for its clipper
OneNote for school notes,
StandAlone MD Files for notes,
Quiver Programming Notes,
IAwriter for scripts

My folders are a complete mess with different kind of links for each set of notes.
It would be great to batch convert links to obsidian links

**Comment by janpeeters70** [comment]
I would love this in addition too!

**Comment by mnaoumov** [comment]
this plugin's philosophy is discourage from using Wikilinks. See README for more details.

Closing this FR
