### ISSUE TITLE
Запрос функции: добавить возможность исключения преобразования ссылок и вложений, ссылающихся на другие заметки

### ISSUE THREAD

**Issue by A-N-P** [dy-sh/obsidian-consistent-attachments-and-links#19]
Здравствуйте!
Плагин отлично работает, даже если в параметрах Obsisdian включено использование Wiki-ссылок, формат новых ссылок «самый короткий путь к файлу из возможных». В этом случае, например, если преобразовывать «короткие ссылки на картинки png» в «makdown ссылки с относительными путям», то все основные функции плагина по отслеживанию местоположения вложений картинок и перемещению их вместе с заметкой - работают. При этом сохраняется удобные функции Wiki-ссылок в обсидиане, и совместимость ссылок на вложения картинок и других фалов - в других редакторах. Но при такой настройке обсидиана ссылки на вложения приходится преобразовывать в md-ссылки сторонними средствами, поскольку функции плагина распространяются на все типы вложений, включая вики-вложения других заметок. В текущей реализации, функция «Convert all embed paths to relative» - оказывает влияние, в том числе и на вложения других заметок, а последующее преобразование таких ссылок в makdown формат, делают неработающими функции всплывающих окон ссылок на заметки и функции вкладывания одной заметки в другую в обсидиан. При этом запуск функции Collect all attachments - коллекционирует по соответствующим папкам не только картинки и прочие вложения, но и перемещает в них вложенные md-файлы заметок.

Чтобы одновременно функциональность «wiki-ссылок вложений заметок в заметки» в обсидиане сохранялась, и все функции плагина распространялись бы только на вложения картинок, и других поддерживаемых не md-файлов, хотелось бы иметь возможность исключать ссылки на заметки из преобразования командами плагина, либо выбирать конкретные типы вложений, вложения которых могли бы подвергаться преобразованию командами плагина. 

Либо просто сделать отдельный ряд функций, распространяющихся допустим только на картинки (либо на все «не md файлы»):
- какой-то аналог функции «Replace all wikilinks with markdown links», распространяющийся только на вложения картинок; 
- аналог функции «Convert all embed paths to relative», но «только для вложенных картинок»;
- аналог функции «Collect all attachments», но «только для вложенных картинок».
- аналог функции «Reorganize vault», выполняющий три предыдущие команды «только для вложенных картинок».

Огромное Вам спасибо! За плагин, за идеи, заложенные в нём, и за Ваш великолепный видеокурс.

**Comment by dy-sh** [comment]
Здравствуйте. Спасибо за отличное предложение!

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
