### ISSUE TITLE
Note links detection performance is very low in big vaults

### ISSUE THREAD

**Issue by mnaoumov** [dy-sh/obsidian-consistent-attachments-and-links#25]
In the code

https://github.com/dy-sh/obsidian-consistent-attachments-and-links/blob/master/src/links-handler.ts#L634

we traverse every single note every time we look for links to file, which is a lengthy operation in big vaults

I found a useful function that supposedly might help to improve the performance dramatically

```js
app.metadataCache.getBacklinksForFile();
```

but this method is not mentioned in the official Obsidian API documentation https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts so I am not sure if we can use it safely.

**Comment by mnaoumov** [comment]
Created corresponding issue for Obsidian API
https://github.com/obsidianmd/obsidian-api/issues/58

**Comment by mnaoumov** [comment]
After some reverse engineering of Obsidian API, I found that `app.metadataCache.getBacklinksForFile()` is not as useful as I thought because `MetadataCache` doesn't keep track of backlinks as I initially thought and it rebuilds it on every call

**Comment by dy-sh** [comment]
To be honest, I don’t remember how it worked, but there is a feeling that I tried to bypass the cache, because there were some problems with it.

**Comment by mnaoumov** [comment]
In my vault with 20k notes, the current implementation is not practical. I just switched to use cached version and it worked for me fine. I can send a PR for that if needed

**Comment by dy-sh** [comment]
If everything works great, then why not.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.8
