### ISSUE TITLE
How to permanently close the update link prompt?

### ISSUE THREAD

**Issue by 1039009892** [dy-sh/obsidian-consistent-attachments-and-links#29]
1. The `Automatically update internal links` option is turned off.
2. Every time I insert an image, the `Update link` prompt keeps appearing.
3. I want to know how to turn off the prompt completely. 

![image](https://user-images.githubusercontent.com/38580693/164844368-c40b283a-2bc1-44a5-bc92-463aaef9e159.png)

![Attachment Name Formatting image 4](https://user-images.githubusercontent.com/38580693/164844114-c0610ab5-2186-44ef-8993-b3fd1c42bb25.png)

Thank you very much for your answer.

**Comment by dy-sh** [comment]
This message is nailed into the obsidian. I asked the obsidian developer about it, he replied that there was no way to turn it off. This is very annoying, but there is no solution.

**Comment by 1039009892** [comment]
您好，我已收到邮件，将尽快查看。

**Comment by dy-sh** [comment]
You can write to the developer of obsidian with a request to make this message disabled. Perhaps he will do this after the next appeal.

**Comment by 1039009892** [comment]
Thank you for your reply and I hope this problem will be solved soon.
