### ISSUE TITLE
Link compatibility with Obsidian features

### ISSUE THREAD

**Issue by j-peeters** [dy-sh/obsidian-consistent-attachments-and-links#31]
Hi Dimitri, 

Thanks for developing this plugin!
You wrote: "If you still want to have link compatibility with some Obsidian features, write a feature request to the github repository of this plugin."

I'm one of those users that, although I can understand that Markdown compatibility is key, would love if all the smart things that Obsidian does with links would still work. I'm right at home in Obsidian and if at any time I would need to use the files in another app I could still use your plugin to convert everything to become markdown compliant. 

I love the smart linking functions and hope to be able to keep using those. 
Would you have time to make your plugin more compatible with this smart linking? 
It would be a great help. Thanks!

**Comment by jocundmo** [comment]
yes, would you please add a setting allow to use wikilink?

**Comment by mnaoumov** [comment]
The plugin is more toleratable towards wikilinks since https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0

Feel free to reopen the issue if some use cases are still not uncovered
