### ISSUE TITLE
[feature suggestion] filename adjustment

### ISSUE THREAD

**Issue by pcause** [dy-sh/obsidian-consistent-attachments-and-links#32]
It would be really useful to have a command that adjust filenames so that characters that aren't legal in Win/Linux/MacOS are removed, spaces changes to dash (-) or underscore (-) and all links are adjusted.  this is useful both as a batch command and ongoing (fix up a file name when created/modified).  If I save a page using MarkDownloader this would be great to have.

**Comment by mnaoumov** [comment]
Files with incorrect symbols cannot be created, so the plugin can't do anything about them
