### ISSUE TITLE
"Move attachments with notes" doesn't work if the link is not an embedded link

### ISSUE THREAD

**Issue by cleanboyjao** [dy-sh/obsidian-consistent-attachments-and-links#33]
The function works fine when the link is in embedded format.
`![Pasted image 20220516131253](Assets/Pasted%20image%2020220516131253.png)`

But if it is a normal link, the attachment will not move with the note. (sometimes I don't want to embed images or other files, I just want to paste their links)
`[Pasted image 20220516131253](Assets/Pasted%20image%2020220516131253.png)`

Is this what the plugin wants or am I misunderstanding something?

**Comment by mnaoumov** [comment]
Fixed in Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
