### ISSUE TITLE
compatibility with tasks queries

### ISSUE THREAD

**Issue by pcause** [dy-sh/obsidian-consistent-attachments-and-links#34]
Thanks for this plugin.  I use the tasks plugin and have a template that uses the 

\`\`\`tasks

query to drop tasks due today into my daily notes.  works fine, but my task has a link to a note related to that task and in the tasks file the note is ,,/,,/somedirectory/note.md after running the plugin.  But that doesn't work when included in the daily note as the link is relative to the todos note location and now the daily note location.

Need someway to resolve this, if possible.  I wonder if this also impacts dataview generated material as well.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0
