### ISSUE TITLE
"Collect attachments in current note" cannot work for notes within different folders

### ISSUE THREAD

**Issue by greatqs** [dy-sh/obsidian-consistent-attachments-and-links#37]
Issue found on plugin version 1.0.8 but not sure whether it works on previous versions.

Case1: noteA and noteB in the SAME folder. 
If contents (contain attachements in noteA) are copied from noteA to noteB, after running this "Collect attachments in current note" command, the plugin works perfect to "collect" the attachement locally for noteB.

Case2: noteA and noteB are in DIFFERENT folders. 
If I do the same as above like case1, this plugin cannot work to "collect" the attachement. All attachements remain as links to noteA.

Please fix this issue for this nice plugin :-)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.9
