### ISSUE TITLE
Wiki-links

### ISSUE THREAD

**Issue by Evgeny1503** [dy-sh/obsidian-consistent-attachments-and-links#39]
1. Вики ссылка на картинку вида:
![[Картинка.имг|200]]  с указанием размера превьихи, конвертируется в такой вид:
![](Картинка.имг) - размер не сохраняется. Плюс, возможно было бы лучше добавлять ей имя в квадратных скобках.

2. Ссылки на заголовки, предложения:
Есть две заметки note1 и note2.
В note2 есть ссылка на note1 вида:
[[note1#header]], которая конвертируется к виду [note1 > header](note1#header). 
Нельзя ли сделать, чтобы если в названии заметки нет алиаса([note1#header|some_name]), то новое имя было до знака '>', т.е. просто note1 ?
А ещё, в ссылке(в круглых скобках) не хватает расширения фала, из-за чего ваш плагин ругается на битые ссылки. Т.е. вместо (note1#header) нужно чтобы было (note1.md#header), но при этом сами ссылки работают.
Тоже и для ссылок на предложения справедливо.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.1.0
