### ISSUE TITLE
"Check consistent" do not recognize path relative to base path (vault path) 

### ISSUE THREAD

**Issue by bill-mao** [dy-sh/obsidian-consistent-attachments-and-links#41]
Attachments links relative to vault path will be recognized as broken link

**Comment by dy-sh** [comment]
Such links are considered invalid. This is done on purpose, because, the plugin promotes the idea that all links should be relative. For example, if you upload notes to github, links relative to the base path will not work either.

**Comment by dy-sh** [comment]
Use the "Convert all link paths to relative" function to make all links relative.

**Comment by bill-mao** [comment]
I thought it would be easier to manage attachment using link relative to base path, when I move markdown. I do not need to update link. But it is less compatible. 
You are right, using tools to update link may be a better choice.
It helps, thank you.

**Comment by bill-mao** [comment]
I thought it would be easier to manage attachment using link relative to base path, when I move markdown. I do not need to update link. But it is less compatible. 
You are right, using tools to update link may be a better choice.
It helps, thank you.
