### ISSUE TITLE
Feature Request : A setting to Convert All Markdown Links to WikiLinks

### ISSUE THREAD

**Issue by 1nsp1r3rnzt** [dy-sh/obsidian-consistent-attachments-and-links#43]
I accidently clicked ` Convert All WikiLinks to Markdown Links` and couldn't find any setting to convert to WikiLinks again. It would be awesome to have an option to convert Markdown to Wikilinks as well.

**Comment by Artin7** [comment]
yes me too! It takes for ever to fix it manually.

**Comment by jocundmo** [comment]
please add a setting to allow disable "convert all wikilinks to markdown links".

**Comment by 1nsp1r3rnzt** [comment]
One of the easier solution is to use [Obsidian Link Converter Plugin](https://github.com/ozntel/obsidian-link-converter) which can convert All Wikilinks to Markdown links on a note.

**Comment by bololodev** [comment]
It would be really nice, I accidentally converted all my 500 notes and forgot to backup. Unfortunately [Obsidian Link Converter Plugin](https://github.com/ozntel/obsidian-link-converter) messes up the links even more.

**Comment by mnaoumov** [comment]
@perigozin If `Obsidian Link Converter` messed up something, it is a good idea to open the issue in their repo

This plugin's philosophy is discourage from using Wikilinks. See README for more details.

So I am closing this FR
