### ISSUE TITLE
Feature Request : Attachment subfolder supports root path

### ISSUE THREAD

**Issue by muzhi1991** [dy-sh/obsidian-consistent-attachments-and-links#44]
starts with "./" use relative path, otherwise in root of obsidian vault root.

**Comment by a616766585** [comment]
I also need this feature because all of my attachments are stored in a folder

**Comment by mnaoumov** [comment]
Starting from https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0 , attachment folder is not managed by this plugin. See https://github.com/dy-sh/obsidian-consistent-attachments-and-links/blob/master/README.md
