### ISSUE TITLE
getting back to normal

### ISSUE THREAD

**Issue by Artin7** [dy-sh/obsidian-consistent-attachments-and-links#47]
I'd converted my wiki-links to relative and my work flow messed up. can you add a command to convert them back?
It would be great if each covert command had a reverse.

**Comment by mnaoumov** [comment]
@Artin7 this plugin's philosophy is discourage from using Wikilinks. See README for more details.

To convert links to/from wikilinks there plugins like https://github.com/ozntel/obsidian-link-converter
