### ISSUE TITLE
Link update stop in continuous operation

### ISSUE THREAD

**Issue by ribber** [dy-sh/obsidian-consistent-attachments-and-links#5]
When I rename a folder which has much files, the process is slow.
If I rename another file before last process finish, last process will stop.
I must wait the notification of process finish，and can't do any other thing.
if I swtich to anther window，I will miss the notification，so I don‘t know if the process is finished.
I think make the notification as a alert may be helpful

**Comment by derwish-pro** [comment]
Thank you for your feedback. I will try to implement a progress bar in the bottom pane of the window.

**Comment by mnaoumov** [comment]
Implemented in Implemented in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0
