### ISSUE TITLE
wrong movement of transclusion markdown note as attachment.

### ISSUE THREAD

**Issue by jocundmo** [dy-sh/obsidian-consistent-attachments-and-links#50]
e.g. if transclude  B.md note in A.md (use "![B.md](B.md)"), click "re-organize vault" will move B.md as the attachment of A.md.
This could mess around the entire notes organization.

**Comment by mnaoumov** [comment]
Fixed in #67

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.1.0
