### ISSUE TITLE
Проблема при перемещении заметок ссылающихся на одинаковые файлы

### ISSUE THREAD

**Issue by exeegen** [dy-sh/obsidian-consistent-attachments-and-links#52]
если две заметки ссылаются на одинаковые файлы, при перетаскивании конфликтующие файлы остаются в первоначальной папке, а ссылка в заметке не изменяется, приходится вручную запускать команду "реорганизовать волт" тогда все приходит в норму. Записал скрин https://youtu.be/4sv6h2reutY

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
