### ISSUE TITLE
Turn off "Automatically update internal links" when "Use build-in Obsidian link caching to process moved notes" is checked?

### ISSUE THREAD

**Issue by SchittBull** [dy-sh/obsidian-consistent-attachments-and-links#53]
Hello,
thank you very much for this plugin!

Do I still have to Turn off "Automatically update internal links" in the Obsidian settings when "Use build-in Obsidian link caching to process moved notes" is checked in the plugin settings?

**Comment by mnaoumov** [comment]
I think you should keep the setting on
