### ISSUE TITLE
Move attachments with note is invalid

### ISSUE THREAD

**Issue by StrollStars** [dy-sh/obsidian-consistent-attachments-and-links#54]
Attachments to a note are in the attachments folder under the folder it is in. After I moved the note, the attachment was still in the original folder. The names of the notes and attachment folders are all in Chinese, does it not support Chinese?

**Comment by jiyee** [comment]
It seems have since been fixed, try the latest version of the plugin.
or provide me with more information plz.

**Comment by StrollStars** [comment]
@jiyee Thank you.
