### ISSUE TITLE
Iphone app fails to load plugin and display an error message

### ISSUE THREAD

**Issue by deneuxa** [dy-sh/obsidian-consistent-attachments-and-links#55]
When the plugin is installed, the iphone App will not succeed to load the plugin.

Main problem is then that , afterthat, it will not correctly update existing notes.

**Comment by marconoris** [comment]
I have the same issue...

**Comment by BobWs** [comment]
Same issue and also with the unique attachment plugin! Only on iOS iPhone on the iPad it’s working just fine!

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
