### ISSUE TITLE
New and unexpected errors

### ISSUE THREAD

**Issue by marconoris** [dy-sh/obsidian-consistent-attachments-and-links#56]
Plugin suddenly stops working on iOS (like this issue #55) and stops to move linked images when a I move a file... or it takes several minutes before moving them. I have to restart obsidian but after first note moved, plugin stop working...

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
