### ISSUE TITLE
What proprietary things would we be giving up to use this plugin?

### ISSUE THREAD

**Issue by qazero** [dy-sh/obsidian-consistent-attachments-and-links#58]
The readme.md mentions the following mentioned below. But what proprietary things would we be giving up? Could you please provide a list of everything we'd be giving up? It would be helpful to include this in the readme.md as well. :)

> To use this plugin, you will have to give up all the proprietary things that Obsidian uses in the link format.
> 
> Obsidian has a very clever file link search, but this can be a problem for you if you want your notes to be compatible with other programs. This is the main point of the plugin.
> 
> If you still want to have link compatibility with some Obsidian features, write a feature request to the [github repository](https://github.com/derwish-pro/obsidian-consistent-attachments-and-links/issues) of this plugin.

**Comment by mnaoumov** [comment]
@qazero list of the Obsidian settings that have to be set to "give up" the proprietary things are mentioned in README under [How to configure Obsidian](https://github.com/dy-sh/obsidian-consistent-attachments-and-links#how-to-configure-obsidian) section
