### ISSUE TITLE
Attachments are removed intermittently

### ISSUE THREAD

**Issue by mnaoumov** [dy-sh/obsidian-consistent-attachments-and-links#59]
If you have multiple plugins that do rename at the same time, current plugin can remove the attachment because of some race conditions.

In my case it was because of the race condition between current plugin and https://github.com/RainCat1998/obsidian-custom-attachment-location

**Comment by Jamsa** [comment]
This issue happened again, in the latest version.

**Comment by Jamsa** [comment]
The attachments were not removed, the note does

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.9
