### ISSUE TITLE
Меняется кодировка в линках к кириллицы на %B3%20%D0%9A%D0%BE%D0%BD%

### ISSUE THREAD

**Issue by aZZmNZtA** [dy-sh/obsidian-consistent-attachments-and-links#6]
Здравствуйте Дмитрий!

Плагин перерабатывает ссылки - всю кириллицу кодирует, т.е. если ссылка, например, такая:

`[6 MOC Сайт WP Скрипты Комп](6%20Сайт%20WP%20Скрипты%20Комп/6%20MOC%20Сайт%20WP%20Скрипты%20Комп.md)`

плагин ее кодирует в такую:

`[6 Сайт WP Скрипты Комп](6%20%D0%A1%D0%B0%D0%B9%D1%82%20WP%20%D0%A1%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D1%8B%20%D0%9A%D0%BE%D0%BC%D0%BF/6%20MOC%20%D0%A1%D0%B0%D0%B9%D1%82%20WP%20%D0%A1%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D1%8B%20%D0%9A%D0%BE%D0%BC%D0%BF.md)`

вот скрин:
https://i.imgur.com/5j52fu4.jpg

Работоспособность ссылки не нарушается, но проблема в том, что подобные ссылки невозможно прочесть, оценить, т.е. по пути уже непонятно, где лежит этот файл. Это уже никак нельзя назвать "хлебными крошками".

1. Можно сделать так, чтобы плагин этого не делал?
2. Можно ли добавить фичу, чтобы плагин наоборот сделал, т.е. то что уже он кодировал, опять перевел в кириллицу?
3. Можно избавиться от кодировки пробела(%20)?

Спасибо!

**Comment by derwish-pro** [comment]
Здравствуйте. Могли бы вы на скриншоте продемонстрировать как именно меняется кодировка? В текстовом описании не совсем понятно, возможно гитхаб еще как-то кодирует ваше сообщение.

**Comment by aZZmNZtA** [comment]
обновил/добавил скрин

**Comment by mnaoumov** [comment]
Links are not encoded anymore (can't even find in which version it behaved like that).
Regarding `%20`, you can't have them replaced out of the box, but you can use [Better Markdown Links](https://obsidian.md/plugins?id=better-markdown-links) plugin for that
