### ISSUE TITLE
FR: добавить ⚠️⚠️⚠️ на верхушку файла ReadMe 

### ISSUE THREAD

**Issue by anatoliibakhtin** [dy-sh/obsidian-consistent-attachments-and-links#64]
Warning signs⚠️⚠️⚠️ you need to make a backup before using the plugin!

**Comment by dy-sh** [comment]
Done. Thank you!

**Comment by mnaoumov** [comment]
Implemented in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.9
