### ISSUE TITLE
Please publish new release

### ISSUE THREAD

**Issue by mnaoumov** [dy-sh/obsidian-consistent-attachments-and-links#65]
There are a few important changes made since release 1.0.8 that worth be published.

In case if you can't maintain the plugin, I can suggest myself as an additional maintainer

**Comment by dy-sh** [comment]
Hello. I invited you to join the collaboration.

**Comment by mnaoumov** [comment]
@dy-sh thank you!

I published [1.0.9](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.9) release

**Comment by dy-sh** [comment]
Great! Thank you very much for your assistance!
