### ISSUE TITLE
.canvas files are unexpectedly moved to attachments folder

### ISSUE THREAD

**Issue by gyouzazuoyg** [dy-sh/obsidian-consistent-attachments-and-links#66]
I basically use .canvas files as part of my notes rather than attachments. I believe most people don't consider Canvas as attachments, right? There is indeed an "ignore files" option in the settings, but I tried "*.canvas" and it didn't work. I think it would be best to allow ignoring files based on file type.

**Comment by jiyee** [comment]
fixed in #67
