### ISSUE TITLE
BUG: Collect attachments moved a bunch of notes into attachments folders

### ISSUE THREAD

**Issue by jayv** [dy-sh/obsidian-consistent-attachments-and-links#69]
version:1.0.9

I'm not sure when it happened first, but today I noticed some of my notes showing up in my attachment folders, mainly notes that were referenced from other notes. 
I manually had to clean things up, but after running "collect all attachments" it seemed to reproduce the problem. 
"Collect attachments in current note" also does the same thing whenever it references a note like `[[some note]]` , I guess this is what you refer to as the "wiki links". 

Consider adding unit tests and some filter on `.md` files except for the `.excalidraw.md` files.

Thanks for an otherwise great plugin.

**Comment by jayv** [comment]
Reading your readme a bit more in detail I now better understand your intent for this plugin, it looks like I will need to find another plugin, I tried the markdown links, but the UX penalty in Obsidian is not worth it.

**Comment by jiyee** [comment]
It has been fixed in v1.1.10.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.11
