### ISSUE TITLE
BUG: collect all attachments and moving file result diffs

### ISSUE THREAD

**Issue by jiyee** [dy-sh/obsidian-consistent-attachments-and-links#70]
The result of collect all attachments and moving file is different, Like:

F1/file.md contains assets/IMG.png, using wiki link like ![[IMG.png]], with the option of attachment folder is set "./assets"
when moving the F1/file.md to F2/file.md, the attachment will relocated to F2/IMG.png, not F2/assets/IMG.png.
perform collecting all attachments, the attachment will relocated to F2/assets/IMG.png.

The result depends on whether the option contains ${filename}, I think two behavior should yield same result.

PS: It only happens while not using the required configuration in README, especially not configure **"New link format": Relative path to file.**

**Comment by jiyee** [comment]
I want to make sure that this issue is being followed or not, and if not, I can close the issue along with the PR.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.11
