### ISSUE TITLE
Consistency Report Showed Bad Links After Run Reorganise Vault

### ISSUE THREAD

**Issue by kennygokh** [dy-sh/obsidian-consistent-attachments-and-links#72]
Hi,

I am not sure why the consistency report displayed Bad Links of about 321 links. I have run Reorganise Vault a few times but bad links still remain. Is this correct behavior as I thought bad links should go away after the run. Please advise.

**Comment by mnaoumov** [comment]
@kennygokh please provide a sample of the vault with the issue
