### ISSUE TITLE
update/re-install fails on version 1.0.11

### ISSUE THREAD

**Issue by southern-tools** [dy-sh/obsidian-consistent-attachments-and-links#74]
Upgrading/Installing version 1.0.11 fails. 

The console shows:

![image](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/assets/19240340/9d5cf322-a4b4-4e5f-b542-739d224a2f6f)

Thank you very much for the plugin, is really useful

**Comment by mnaoumov** [comment]
Fixed

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.11
