### ISSUE TITLE
plugins crashes my obsidian

### ISSUE THREAD

**Issue by cvh-obsi** [dy-sh/obsidian-consistent-attachments-and-links#75]
I have and use daily my vault (more than3000 notes).
I installed this plugin 2 or 3 times, 
tried the consistency check and
.. it crashes my obsidian EACH TIME
I get a gey empty page and that's it
I have to uninstall and reinstall obsidian to make it work again
impossible to open development mode to see the error

**Comment by mnaoumov** [comment]
@cvh-obsi thanks for your report. I have 50k notes and I don't experience such behavior.

Do you have the experimental caching setting turned on?

Can you open developer tools before running the problematic command?

If this doesn't help, can you provide a copy of your vault for investigation?

**Comment by cvh-obsi** [comment]
Thanks for your quick answer
I’ll test again
And keep you posted based on your input



***@***.***

**Comment by cvh-obsi** [comment]
I made the test and activated the developper view before launching
And I got the same blank screen, with devtools disconnected


￼
Christian

**Comment by mnaoumov** [comment]
@cvh-obsi did you enable the caching setting of the plugin?

**Comment by cvh-obsi** [comment]
And now I always get this grey blank screen after 1 or 2 seconds where I see the page that seems to be the result page of the consistence check
And I cannot do anything

I deleted the plugin from the plugin folder and even deleted it from the .json of the communitiy plugin
And Obsidian stays blocked on this grey page

Maybe a conflict with another plugin?

**Comment by cvh-obsi** [comment]
I didn’t do anything the plugin’s options

Here a video when the problem has happened (call of command « check consistence… » )
The vault is corrupted

The video: https://youtu.be/pywGlkjVgxw
The vault￼

Hope you’ll find something as your plugin is precious (to export notes to another vault)

**Comment by mnaoumov** [comment]
@cvh-obsi this problem is caused by out-of-memory. Try to disable all plugins and check them one by one

**Comment by mnaoumov** [comment]
I don't think it's the issue of this plugin. But you better check the experimental setting I mentioned before. It might improve some memory consumption

**Comment by cvh-obsi** [comment]
Good to know
Thanks

I’ll make some experiments


***@***.***
