### ISSUE TITLE
Localizing images destroys tables

### ISSUE THREAD

**Issue by gerroon** [dy-sh/obsidian-consistent-attachments-and-links#76]
Hi

I like this plugin a lot but there is a downside. It destroys tables if the images are in tables. You can test it with the page below yoursel. Copy and paste the page then run localize attahcments

https://github.com/nerdyrodent/AVeryComfyNerd

thanks

**Comment by mnaoumov** [comment]
What do you mean by `Localize Attachments`? This plugin doesn't have such command

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0
