### ISSUE TITLE
How to convert all links to the shortest path when processing a file.

### ISSUE THREAD

**Issue by HWiwoiiii** [dy-sh/obsidian-consistent-attachments-and-links#77]
For instance, an image is attached to a file with the shortest link [[image.jpg]] (no path included). When I move the file to another folder, the link automatically changes to [[folder1/folder2/folder3/image.jpg]]. Is it possible to stay in the original link format? (shortest wiki link)

Could you please add a command that allows users to change all links with paths [[folder1/folder2/folder3/image.jpg]] to the shortest [[image.jpg]], deleting all paths in front of the file name?

Moreover, is it possible to only convert internal file links without changing web links?

![image](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/assets/103039908/c7c81424-3bfc-4681-84c7-a88626a28260)

Finally, thank you for this amazing plugin!

**Comment by mnaoumov** [comment]
Implemented in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
