### ISSUE TITLE
"Path is a directory" error

### ISSUE THREAD

**Issue by severdia** [dy-sh/obsidian-consistent-attachments-and-links#78]
I created a new vault to test this plugin with and ran the plugin, but got the following console error.

![Screenshot-2024-01-01-at-2 53 27 PM](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/assets/355924/aea79fc2-7d3a-4687-a0c8-38e4a5c557f3)

The message says "Fixing consistency for 3688 renamed files...", but the plugin has stopped working.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0
