### ISSUE TITLE
The plugin moves my embedded pages. help

### ISSUE THREAD

**Issue by mrdrbrdr** [dy-sh/obsidian-consistent-attachments-and-links#79]
The plugin is messing up my system of filestoring. I have a rutine of embedding pages into others, using "**![['embedded_page]]**", however, the plugin seems to register those embedded pages as yet another attachment and moves those. Moreover, those embedded files are thus moved, and _their_ attachments are moved too.. its one big mess. Is there a way to make it not do that? 

put in a different way; Is there a way to make the plugin only change the location of attachments files such as jpg, png, mp3, ect, only so that embedded pages are left alone?

**Comment by Moyf** [comment]
![image](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/assets/4013062/221e9ecd-232c-496f-8ce7-ea64150dadf0)

Same problem here, when Move a note with ![[EmbedPage]], it will move (copy?) the embedded page into the Assets folder.
Hope this plugin could define only attachments with specific extension would be moved. (Especially to exclude the .md files)

**Comment by Moyf** [comment]
Tried to make a quick fix:
![image](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/assets/4013062/28ec5776-f737-4ffa-89f5-958ac7c54452)

Add these lines in `main.js` after line 1584:

```js
            if (path.endsWith(".md")){
                console.log(`Ignoring ${path} as it is a markdown file`)
                return result;
            }
```

So when the plugin is going to move a file and detect ".md" extension, it would just NOT move it.

It works for me, though I'm not sure if it would cause other problems 🤔

**Comment by mnaoumov** [comment]
https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.0.0
