### ISSUE TITLE
Обновление кеша ссылки - конфликтует с работой obsidian Sync

### ISSUE THREAD

**Issue by aZZmNZtA** [dy-sh/obsidian-consistent-attachments-and-links#8]
Здравствуйте, Дмитрий!

Я вам писал про массовое удаление файлов. Нашел причину.

Вот запись лога консоли:

 links-handler.ts:514 Consistent attachments and links: link updated in cached note [note, old link, new link]: 
  папка1/тестовый.md
   _attachments/1da6618f2df5ed78f9d72ade74f3ae6b.jpg
   1da6618f2df5ed78f9d72ade74f3ae6b.jpg

После того как кеш обновился и я запускаю синхронизацию - идет массовое удаление 

2021-06-19 08:52 - Deleting remote file  папка1/_attachments/1da6618f2df5ed78f9d72ade74f3ae6b.jpg

**Видимо, каким-то образом функционал obsidian Sync считает что файл был удален, 
после того как ваш плагин обновил по нему информацию в кеше.**

Вот ветка где есть доп. информация - https://forum.obsidian.md/t/obsidian-sync-spontaneous-deletion-of-pictures/19727/11?u=friendlmickle

**Comment by mnaoumov** [comment]
Don't seem to be an issue anymore
