### ISSUE TITLE
links in code blocks

### ISSUE THREAD

**Issue by pcause** [dy-sh/obsidian-consistent-attachments-and-links#81]
Just ran the latest and the report pointed to this in the note:

\`\`\`html
\<img  src="workplace.jpg"  alt="Workplace"  usemap="#workmap"  width="400"  height="379"/><map name="workmap">  \<area    shape="rect"    coords="34,44,270,350"    alt="Computer"    href="computer.html"  />  <area    shape="rect"    coords="290,172,333,250"    alt="Phone"    href="phone.html"  /> \<area    shape="circle"    coords="337,300,44"    alt="Cup of coffee"    href="coffee.html"  /></map>
\`\`\`

I don't think that the plugin should be scanning inside code blocks.  Perhaps an option to enable disable scanning in code blocks

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0
