### ISSUE TITLE
Update references， When renaming/move the md file in the resource manager of the operating system

### ISSUE THREAD

**Issue by 1067237855** [dy-sh/obsidian-consistent-attachments-and-links#86]
This plugin is so great! When I move a md note in Obsidian, the plugin checks if attachments need to be moved and links updated. 

I would expect that move file/renames title would update references When renaming the md file in   ⭐⭐⭐**the resource manager of the operating system**⭐⭐⭐   other than obsidian. This becomes very problematic when consolidating & summarizing notes. Now a significant amount of effort has to be put into listing out all reference points up manually updating them.
That’s a LOT of friction, and a LOT of error.

So many people have mentioned this issue, but no one has ever solved it. This plugin of yours, Big Brother, is the closest approach solution, and I hope it will be considered if the feature can be implemented.

https://forum.obsidian.md/t/broken-links-in-relative-path-mode-on-move-rename/4386

**Comment by mnaoumov** [comment]
@1067237855 Actually Obsidian tracks the file system changes and such changes should be picked up by the plugin anyways. Can you please provide a sample vault and video reproducing the issue?
