### ISSUE TITLE
Need move attachments to subfolders

### ISSUE THREAD

**Issue by itoldusoandso** [dy-sh/obsidian-consistent-attachments-and-links#88]
Would be great to be able to move attachments e.g. “**Agreement123**” inside **.attachments** folder in a subfolder there called “Contracts”? 

Example:

The note would be saved here:

**Vault > Legal > ... note name "Contracts"**

I want attachments to be saved here:

**Vault > Legal > .attachments > Contracts > ..... here comes attachment "Agreement123".**

Thanks.

**Comment by mnaoumov** [comment]
@itoldusoandso 

1. Using dot-folders `.attachemnts` is a bad idea, because Obsidian doesn't track changes to such folders.
2. Your scenario is covered via `Attachment Subfolder` setting set to `./.attachments/${filename}`
