### ISSUE TITLE
Support 'jump to XX page' for link to a PDF file

### ISSUE THREAD

**Issue by zhaoruibing** [dy-sh/obsidian-consistent-attachments-and-links#9]
**Issue**: 
- When running "check vault consistent", it labels links to local PDF as inconsistent if there is a page number at the end of the link.
- Example,
  - `.attachments/foo.pdf` is good
  - `.attachments/foo.pdf#page=3` is inconsistent

**Why Need This?**
In [Obsidian Release v0.10.8](https://forum.obsidian.md/t/obsidian-release-v0-10-8/11323), 
> You can now link to a page of a PDF file by adding `#page=number` at the end. For example` [[My file.pdf#page=3]]`.

~~**Proposed Change**:~~
- ~~Maybe, when parsing local file extname, stop parsing at '#'?~~
- ~~But [it seems technically](https://stackoverflow.com/questions/4814040/allowed-characters-in-filename) '#' can be part of a filename, I am unsure if '#' can exist in the file extension part.~~

Thanks for making this plugin, it makes reorganizing notes such a breeze.

**Comment by mnaoumov** [comment]
I found the fix was not complete. Not-embedded links are still considered as broken

```md
[Theorem 1.2.3](_assets/Book.pdf#page=123)
```

**Comment by dy-sh** [comment]
Thank you!

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/1.0.8
