### ISSUE TITLE
Delete Empty Folders: console error "rm returned EISDIR (is a directory)"

### ISSUE THREAD

**Issue by suka97** [dy-sh/obsidian-consistent-attachments-and-links#90]
I've just installed the plugin and run the commands as listed on the README instructions:

1. Replace All Wiki Links with Markdown Links
2. Convert All Embed Paths to Relative
3. Convert All Link Paths to Relative
4. Collect All Attachments
5. Delete Empty Folders

All run without issues until step 5. The command didn't display any messages, so I checked the command log:
![image](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/assets/49660888/5e999a71-7cc7-456a-9b34-63d89cb57672)

I've tried manually deleting this specific folder "C:\Users\asukanec\OneDrive - Grupo Mirgor\Desktop\Notas Mirgor\Test\sub\_assets" but the issue remained, now with another empty folder throwing the error.

I'm using Obsidian v1.5.12 on Windows 11 and plugin v1.3.0

**Comment by mnaoumov** [comment]
@suka97 Should be fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0

Feel free to reopen the bug if it is still happening

**Comment by suka97** [comment]
I've updated the plugin to last v2.0.0 but now the plugin doesn't work. When I move a markdown file with an attachment it does not move the attachment. On the console the following error is displayed:

![image](https://github.com/user-attachments/assets/744e5809-b5d8-443f-8fd7-228a6ceb62ce)

So I went back to old v1.3.0 which was working for me (besides this issue)

**Comment by mnaoumov** [comment]
@suka97 can you provide a test vault with the video showing how to reproduce the issue

**Comment by suka97** [comment]
Here is a video of the new issue appearing on v2.0.0, as well as v1.3.0 working as it should (besides not emptying the _assets folder)


https://github.com/user-attachments/assets/cd91fa0a-d196-4e57-b600-ed2b3d2c4387


https://github.com/user-attachments/assets/8188ad48-dc4d-41e6-8135-03bb75463e58

Here's my sample Obsidian Vault: [ObsidianTemplate.zip](https://github.com/user-attachments/files/16355372/ObsidianTemplate.zip)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.1.0

**Comment by suka97** [comment]
The issue regarding getCacheSafe on v2.0.0 was fixed:

> I've updated the plugin to last v2.0.0 but now the plugin doesn't work. When I move a markdown file with an attachment it does not move the attachment. On the console the following error is displayed:
> 
> ![image](https://private-user-images.githubusercontent.com/49660888/351525886-744e5809-b5d8-443f-8fd7-228a6ceb62ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTkwMjksIm5iZiI6MTcyMjUxODcyOSwicGF0aCI6Ii80OTY2MDg4OC8zNTE1MjU4ODYtNzQ0ZTU4MDktYjVkOC00NDNmLThmZDctMjI4YTZjZWI2MmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEzMjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZTcwMDliM2Y3MWFlNmU4ODM3YWY1ZGMwNGMzNTU5OWI0MDEyOTJiOTk0MTU1ODE3MTM0MDg4YzZiY2FiMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.frzvK2696klI6uNHgVmD6gvR3pcGA_siTy9Je095pAU)
> 
> So I went back to old v1.3.0 which was working for me (besides this issue)

But the original error "rm returned EISDIR" remained:

> I've just installed the plugin and run the commands as listed on the README instructions:
> 
> 1. Replace All Wiki Links with Markdown Links
> 2. Convert All Embed Paths to Relative
> 3. Convert All Link Paths to Relative
> 4. Collect All Attachments
> 5. Delete Empty Folders
> 
> All run without issues until step 5. The command didn't display any messages, so I checked the command log: ![image](https://private-user-images.githubusercontent.com/49660888/335263974-5e999a71-7cc7-456a-9b34-63d89cb57672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTkwMjksIm5iZiI6MTcyMjUxODcyOSwicGF0aCI6Ii80OTY2MDg4OC8zMzUyNjM5NzQtNWU5OTlhNzEtN2NjNy00NTZhLTliMzQtNjNkODljYjU3NjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEzMjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ODQ2NTA3NzQ1OGE1MWYxZTJiYTQzOTQ2MzgyMTE4OTdkMzhkNjNmZThiNTRlMmMzZGVjNTQ1YTY4MzljYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qJx4StOyA1EMwjELU6gUrs99n_5EJEUTnAe39Skx9wU)
> 
> I've tried manually deleting this specific folder "C:\Users\asukanec\OneDrive - Grupo Mirgor\Desktop\Notas Mirgor\Test\sub_assets" but the issue remained, now with another empty folder throwing the error.
> 
> I'm using Obsidian v1.5.12 on Windows 11 and plugin v1.3.0

I'm testing this with the sample Obsidian Vault attached above
