### ISSUE TITLE
Whenever I move a file, it gives me this error.

### ISSUE THREAD

**Issue by Bluemandan** [dy-sh/obsidian-consistent-attachments-and-links#91]
Love the plugin, but I get this error every time. I don't know if this is because there is another plugin running in contrary or there is a bug with this one.

<img width="601" alt="Screenshot 2024-07-23 222737" src="https://github.com/user-attachments/assets/5947a93d-a518-4637-bbd9-d9a1553db940">
<img width="268" alt="Screenshot 2024-07-23 222708" src="https://github.com/user-attachments/assets/54b67c19-8d18-4614-8682-36a09bee1196">
<img width="300" alt="Screenshot 2024-07-23 222623" src="https://github.com/user-attachments/assets/be1dfe48-8756-4a0e-ba24-1fe606ccf9b7">

**Comment by NyoDavid** [comment]
Experiencing the exact same issue.

**Comment by paschmann** [comment]
+1 - same issue

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.1.0
