### ISSUE TITLE
Errors on non existing files after the recent update.

### ISSUE THREAD

**Issue by qacizar** [dy-sh/obsidian-consistent-attachments-and-links#92]
I have links to non existing files, before the last two updates plugin didn't react on them, now error occurs every time I collect images.

<img width="1061" alt="Снимок экрана 2024-08-04 в 09 48 03" src="https://github.com/user-attachments/assets/8812aa45-28c4-445e-809c-9ce4bc95dddb">

**Comment by mnaoumov** [comment]
@qacizar I cannot reproduce the issue. Can you please provide a sample vault and video reproducing the issue?

**Comment by qacizar** [comment]
https://drive.google.com/open?id=1-JjqmayI0XP6kTPle-u-tNWJubecSMlu&usp=drive_fs

Run "Collect all attachments".

**Comment by mnaoumov** [comment]
@qacizar your vault has plugin version 2.1.0

If you update to the latest, the issue won't occur

**Comment by qacizar** [comment]
My goodness, I've just updated, then ran collect attachments and all the thousands of attachments moved to /, no all Attachments folders are empty and all of them in the /

**Comment by mnaoumov** [comment]
@qacizar hopefully you have backups

I guess you had to read [`README`](https://github.com/dy-sh/obsidian-consistent-attachments-and-links?tab=readme-ov-file#attachment-subfolder-setting)

**Comment by qacizar** [comment]
Открою тебе секрет, никто не читает текст обновлений плагинов и программ. Ты НЕ ЖДЁШЬ, что разрабу ударила моча в голову и он проснулся утром и решил изменить корневые функции.

**Comment by mnaoumov** [comment]
@qacizar обновление мажорной версии может включать BREAKING CHANGES

**Comment by qacizar** [comment]
> @qacizar обновление мажорной версии может включать BREAKING CHANGES

Как скачать предыдущие версии плагина?

**Comment by qacizar** [comment]
> @qacizar обновление мажорной версии может включать BREAKING CHANGES

Проверь механизм обновления плавунов в Obsidian: Check for updates > update. Где в этой цепочке пользователь должен увидеть новый индекс обновления или фразу BREAKING CHANGES?

**Comment by mnaoumov** [comment]
Либо качаешь вручную [Releases](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases)
Либо через плагин [BRAT](https://obsidian.md/plugins?id=obsidian42-brat) > `BRAT: Plugins: Add a beta plugin with frozen version based on a release tag`

**Comment by mnaoumov** [comment]
> > @qacizar обновление мажорной версии может включать BREAKING CHANGES
> 
> Проверь механизм обновления плагинов в Obsidian: Check for updates > update. Где в этой цепочке пользователь должен увидеть новый индекс обновления или фразу BREAKING CHANGES?

хорошая мысль, надо добавить warning после установки

**Comment by qacizar** [comment]
> Либо качаешь вручную [Releases](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases) Либо через плагин [BRAT](https://obsidian.md/plugins?id=obsidian42-brat) > `BRAT: Plugins: Add a beta plugin with frozen version based on a release tag`

Скачал, как заставить это работать? Я не разраб

**Comment by mnaoumov** [comment]
@qacizar если скачал вручную, кладёшь в папку `path/to/vault/.obsidian/plugins/consistent-attachments-and-links`

**Comment by qacizar** [comment]
> @qacizar если скачал вручную, кладёшь в папку `path/to/vault/.obsidian/plugins/consistent-attachments-and-links`

Спасибо, вернул всё назад, инфаркт переносится
