### ISSUE TITLE
error An unhandled error occurred. Please check the console for more information.

### ISSUE THREAD

**Issue by LOVECHEN** [dy-sh/obsidian-consistent-attachments-and-links#93]
error code
```
An unhandled error occurred. Please check
the console for more information.
```

error console
```
plugin:consistent-attachments-and-links:331 SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is a directory) /Users/XXX/Downloads/XXX/XXX/_attachments
```

**Comment by mnaoumov** [comment]
@LOVECHEN need more details what exactly did you do before the issue occurred

**Comment by mnaoumov** [comment]
@LOVECHEN Can you please provide a sample vault and video reproducing the issue?

**Comment by zarkin404** [comment]
When I delete the markdown file, the error message mentioned in this issue also appears. The error stack is as follows:

```
No active editor.
plugin:obsidian-attachment-name-formatting:3552 Formatting attachments...
plugin:obsidian-attachment-name-formatting:3554 Getting attachments list...
plugin:obsidian-attachment-name-formatting:3685 No attachments found...
plugin:consistent-attachments-and-links:579 RangeError: Maximum call stack size exceeded
    at new t (app.js:1:724942)
    at createTFolderInstance (plugin:consistent-attachments-and-links:464:16)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
    at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
```

**Comment by zarkin404** [comment]
> When I delete the markdown file, the error message mentioned in this issue also appears. The error stack is as follows:
> 
> ```
> No active editor.
> plugin:obsidian-attachment-name-formatting:3552 Formatting attachments...
> plugin:obsidian-attachment-name-formatting:3554 Getting attachments list...
> plugin:obsidian-attachment-name-formatting:3685 No attachments found...
> plugin:consistent-attachments-and-links:579 RangeError: Maximum call stack size exceeded
>     at new t (app.js:1:724942)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:464:16)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
>     at createTFolderInstance (plugin:consistent-attachments-and-links:465:23)
> ```
> 
> My obsidian version is 1.6.7 (Installer 1.6.5).

I found that renaming file can also trigger this problem.

**Comment by zarkin404** [comment]
[sample.zip](https://github.com/user-attachments/files/16569087/sample.zip)

The above sample vault can reproduce this problem. You can trigger by rename the `Hello` folder.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.9.0
