### ISSUE TITLE
Attachment Subfolder docs unclear

### ISSUE THREAD

**Issue by notuntoward** [dy-sh/obsidian-consistent-attachments-and-links#94]
I just installed 3.0 of this plugin and saw the popup below:

![image](https://github.com/user-attachments/assets/a1450e1c-a95e-440e-9905-e75da4405435)

But the documents [say](https://github.com/dy-sh/obsidian-consistent-attachments-and-links?tab=readme-ov-file#attachment-subfolder-setting):

> Specify "Attachments subfolder" name in the plugin settings.

Should the docs now instead say something about the *Default location for new attachments*  and *Subfolder name* name in the Obsidian *Files and Links* settings? ?

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.5.0
