### ISSUE TITLE
Reorganize vault ignores default location for new attachments and moves everything to vault root

### ISSUE THREAD

**Issue by brendanator** [dy-sh/obsidian-consistent-attachments-and-links#95]
Here's my config for default location for new attachments

<img width="926" alt="image" src="https://github.com/user-attachments/assets/95b5bddc-1c3d-4eca-999d-a18df6554209">

I ran `Reorganize vault` and all but 3 attachments were moved into the root of the vault

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.9.0

**Comment by brendanator** [comment]
Fantastic, thanks!
