### ISSUE TITLE
Markdown links only for attachments?

### ISSUE THREAD

**Issue by tophee** [dy-sh/obsidian-consistent-attachments-and-links#96]
I like the idea of the plugin to maintain consistent attachments but I would like to keep Wikilinks for linking between notes. Would it be possible to make the plugin compatible with this use case, i.e. to let the plugin do what it does for embedded attachments but not for any other links?

You write that "Use wikilinks" must be turned off in Obsidian settings, so this is probably the key question: how fundamental is this requirement for the plugin to work? Could it be made to work with "Use wikilinks" turned on, e.g. by intercepting only certain links and passing the others on to Obsidian?

**Comment by mnaoumov** [comment]
Updated README

**Comment by tophee** [comment]
I looked at the changes in the ReadMe and I see you removed the requirement to not use wikilinks which is great. But does this address my question about using markdown links for attachments only? 

According to the current ReadMe, I can "Replace All Wiki Links with Markdown Links" but I can't *replace all embed WikiLinks to Markdown*, is that correct? That's what I meant by "let the plugin do what it does for embedded attachments but not for any other links"...

**Comment by mnaoumov** [comment]
@tophee Added [Replace All Wiki Embeds with Markdown Embeds](https://github.com/dy-sh/obsidian-consistent-attachments-and-links?tab=readme-ov-file#replace-all-wiki-embeds-with-markdown-embeds) in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.12.0

**Comment by tophee** [comment]
Sorry, I have to come back to this. It turns out that the new feature doesn't work with the Obsidian Custom Attachment location plugin because that plugin will change the path back to Wikiformat (I suppose because my obsidian setting is "Use Wiklinks"). 

BTW: This in turn seems to trigger your plugin to delete the attachments. Could it be that it reacts immediately when the other plugin deletes the link before replacing it with the wikilink? In that case I would suggest adding a few seconds delay before deleting. Also, I would suggest deleting to the obsidian trash, not the system trash. As a workaround, I am turning the "Delete unused attachments with Note" off for now. - Or is this not even the setting causing the deletion? I realize that it says "with note", i.e. it should trigger when the note is delete, not when the link is deleted. If that is the case, I should figure out which other plugin might be deleting the attachments.

But back to the actual matter: I suppose there is no way for you to stop the other plugin from changing the format back? In that case it might be worth alerting your users to the incompatibility between this command and the other plugin.

Here is another detail, just in case it matters: I have not actually used your plugin to reformat the embedded links yet (because it's an all or nothing command, can't limit it to the current note), so I did the renaming manually to test.

**Comment by tophee** [comment]
Quick update: It looks like it is neither your nor any other plugin that is deleting those files, but Noteplan. So, you can disregard my last comment. Sorry for the confusion.
