### ISSUE TITLE
Convert All Embed Paths to Relative breaks image links

### ISSUE THREAD

**Issue by severdia** [dy-sh/obsidian-consistent-attachments-and-links#98]
I had some issues running "Reorganize Vault" so I decided to take each step individually to troubleshoot. I was able to "Replace All Wiki Links with Markdown Links" as the first step and it appears successful. But when I use "Convert All Embed Paths to Relative", many links break because there's an assumption that the attachments are always in the same folder as the note. Here's a before & after example:

![Screenshot 2024-08-12 at 8 12 25 AM](https://github.com/user-attachments/assets/85a2d321-8f12-4a57-973b-c7dd862dbc02)

The note linking to these images is in a subfolder of "Hiring" and it looks like the plugin is just removing the part of the absolute URL before "attachments" instead of actually checking the hierarchy of the note in relation to the image. Which, of course, results in this:

![Screenshot 2024-08-12 at 8 09 34 AM](https://github.com/user-attachments/assets/b8258666-357a-4a99-9841-8c315d40756a)

Here's what that note looks like after running "Replace All Wiki Links with Markdown Links" before running "Convert All Embed Paths to Relative".

![Screenshot 2024-08-12 at 8 22 09 AM](https://github.com/user-attachments/assets/438c28f4-b0b8-4d7b-af46-082eea59b7e2)

The absolute links are correct, but the relative ones aren't.

**Comment by severdia** [comment]
Here's what that note looks like after running "Replace All Wiki Links with Markdown Links" before running "Convert All Embed Paths to Relative".

![Screenshot 2024-08-12 at 8 22 09 AM](https://github.com/user-attachments/assets/438c28f4-b0b8-4d7b-af46-082eea59b7e2)

**Comment by severdia** [comment]
I figured out why this was happening. It's because the New Link Format setting was set to "Absolute path in vault". Changing this to "Relative path to file" fixed the issue. Maybe there should be a notice in the readme or somewhere in the plugin to check this if it's required?

**Comment by mnaoumov** [comment]
@severdia no, that was a bug, fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.11.0
