### ISSUE TITLE
How to stop it from renaming wiki links into absolute paths?

### ISSUE THREAD

**Issue by Barmaid1076** [dy-sh/obsidian-consistent-attachments-and-links#99]
- after the last update, when I move an image that is linked to a note into another folder, the link in the linked note changed from "![[Pasted image 20240815131816.png]]" to "![[Folder/Pasted image 20240815131816.png]]", how to stop that behavior? 
- How to stop it from deleting attachments when I delete the note that is linked to them?
- Another thing is after the update, when I move a file to another folder, it gives me an error
![image](https://github.com/user-attachments/assets/db99ef04-7298-4139-87d0-4233e637cae1)

**Comment by mnaoumov** [comment]
1. Please check if you have the following setting 
![image](https://github.com/user-attachments/assets/f34adde1-533b-400c-9a52-fcef2c055093)

2. 
![image](https://github.com/user-attachments/assets/b9a78aba-0765-4578-b0b7-c850d7ad48af)

3. That's strange that you have `md` file in `attachments` folder at first place.

Please attach a copy of your vault and video to reproduce your issues.

**Comment by Barmaid1076** [comment]
For question 1, if I use absolute path, obsidian will give a link like "[[BBB/bbb/Pasted image 20240815131714.png]]" when I trying to link an attachment, I have always used shortest path when possible which will use "[[Pasted image 20240815131714.png]]" to link attachment

**Comment by Barmaid1076** [comment]
For question 2, I have that disabled, but it still deletes the attachments

My settings:
![image](https://github.com/user-attachments/assets/bf697cbb-b96a-45c4-a9a8-511fa32a1223)

![image](https://github.com/user-attachments/assets/1737603d-3cfd-43cb-b0ab-df6932ff1aa5)

**Comment by Barmaid1076** [comment]
When I move a note to another folder, it gives an error and delete itself
![image](https://github.com/user-attachments/assets/42ba9dd9-ad1d-4632-bd47-74150dccab54)

**Comment by mnaoumov** [comment]
Are you sure you are using the latest version of the plugin?

**Comment by Barmaid1076** [comment]
> Are you sure you are using the latest version of the plugin?您确定您正在使用该插件的最新版本吗？

![image](https://github.com/user-attachments/assets/cb6cb6d2-0524-485a-ac29-7682315a10fe)

**Comment by mnaoumov** [comment]
Ok, then I need a test copy of the vault with the video

**Comment by Barmaid1076** [comment]
I will try to reinstall the plugin now

**Comment by Barmaid1076** [comment]
[OBtest.zip](https://github.com/user-attachments/files/16621354/OBtest.zip)

**Comment by Barmaid1076** [comment]
[OBtest (2).zip](https://github.com/user-attachments/files/16621373/OBtest.2.zip)
![PixPin_2024-08-15_14-00-42](https://github.com/user-attachments/assets/87fe633a-1b02-4c36-865b-39cf4e2cd6df)

**Comment by Barmaid1076** [comment]
![image](https://github.com/user-attachments/assets/6ebec247-234d-49b5-b1f9-a376b6611780)

**Comment by Barmaid1076** [comment]
> ![image](https://private-user-images.githubusercontent.com/110725436/358118722-6ebec247-234d-49b5-b1f9-a376b6611780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTQ4OTMsIm5iZiI6MTcyMzY5NDU5MywicGF0aCI6Ii8xMTA3MjU0MzYvMzU4MTE4NzIyLTZlYmVjMjQ3LTIzNGQtNDliNS1iMWY5LWEzNzZiNjYxMTc4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDAzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmYzYTEzMzdhN2YzYWFjZTczZDY3ZDRiZTdmYjVlMzM5YmIyNTVlNzU2Mzg5ZWQzMzk0YjQ4NWNlYTZlMzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TL3kUqrtUpQIGHMmCaGS-ieEfmCh_4Td_blgEN8UG5Q)

May I ask why is this setting removed?

**Comment by mnaoumov** [comment]
The `Read more` link leads to the `README` which supposed to explain. If it is still unclear, I guess, I need to put more info into README
